rule "mark web server as failed if load-balancer insists it is"
dialect mvel
when
   $appliance : WebAppliance($ip : ip, $port: port, state == 'reachable')
   Number( intValue > 2 ) from accumulate(
       $failures = LoadBalancerMonitor(
                        webserver_ip == $ip,
                        webserver_port == $port,
                        status == "Not Responding")
                   over window:time( 2m ),
       count( $failures ) )
   not OnApplianceFailed(appliance == $appliance)

then
   modify($appliance) {
        state = 'unreachable'
   }
   request = new OnApplianceFailed($appliance)
   insert(request)
   exitPoint[ "event_bus" ].insert(request)
end
